version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y upgrade
      - apt-get install xvfb python python-pip build-essential apt-transport-https curl zip -y
      - pip install --upgrade pip
      - pip install selenium
      - pip install awscli
      - cp xvfb.init /etc/init.d/xvfb
      - chmod +x /etc/init.d/xvfb
      - update-rc.d xvfb defaults
      - service xvfb start
      - export PATH="$PATH:`pwd`/webdrivers"
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - apt-get update
      - sudo apt-get -y install dotnet-sdk-2.1
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - apt-get install -y nodejs
      - npm install
  build:
    commands:
      - export DISPLAY=:5
      - dotnet restore
      - dotnet build --configuration release
      - dotnet publish --configuration release
      - cd SharkSync.Web.Api.Tests
      - dotnet test
      - cd ../
      - cd SharkSync.Web.Api
      - dotnet lambda package --configuration release --framework netcoreapp2.1
      - cd ../
      - cd SharkSync.Deployment
      - dotnet lambda package --configuration release --framework netcoreapp2.1
      - cd ../
      - bash create-github-release.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank
      - cd SharkSync.Web/bin/Release/netcoreapp2.1/publish/wwwroot
      - zip -r ../../../../../../SharkSync.Web.Html.zip .
      - cd ../../../../../../
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./SharkSync.Web.Api/bin/release/netcoreapp2.1/SharkSync.Web.Api.zip
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./SharkSync.Deployment/bin/release/netcoreapp2.1/SharkSync.Deployment.zip
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./SharkSync.Web.Html.zip
      - bash upload-binary.sh github_api_token=${GITHUB_TOKEN} owner=sharksync repo=sharktank tag=LATEST filename=./cloudformation.yaml
      - aws cloudformation deploy --template-file cloudformation.yaml --stack-name sharksync-web --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - cd SharkSync.IntegrationTests
      - dotnet test